#!/usr/bin/env bash

set -euo pipefail

# rebase a list of branches onto each other
rb_chain() {
	CHAIN=("$@")
	CHEAD=${CHAIN[@]:0:1}
	FIRST=${CHAIN[@]:1:1}
	TAIL=${CHAIN[@]:2}

	for branch in "${CHAIN[@]}"; do
		git checkout "$branch"
	done

	git checkout "$CHEAD"
	git rebase "$CHEAD" "$FIRST"
	git rebase-chain "$TAIL"
}

# sort branches starting with number by name, length; skip first
# BRANCHES=$(git branch | sed -e 's/^ *//' -e 's/^\* //' | grep -E '^\d+' | sort | tail -n +2)
CHAIN1=(
main
01service
02service-metrics
03service-metrics-otel
04service-metrics-prom
05docker
06docker-compose
07docker-compose-otel
08docker-compose-redis
08docker-compose-redis-otel
10microservices
10microservices-autoi
11infra-correlation
)

CHAIN2=(
08docker-compose-redis-otel
09k8s
09k8s-otel
12microservices-k8s
12microservices-k8s-autoi
13custom-instr
)

TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
SNAP=../pre-rebase-snapshot_$TS.tar.zst
echo "creating $SNAP..."
tar --use-compress-program pzstd -cf "$SNAP" .

rb_chain "${CHAIN1[@]}"
rb_chain "${CHAIN2[@]}"
