version: '3'

services:
  wordcount:
    build: .
    expose:
      - "8000"
    ports:
      - "8000:5000"
    environment:
      - REDIS_URL=redis://cache
    depends_on:
      - "redis"
  redis:
    image: redis
    container_name: cache
    expose:
      - "6379"
  collector:
    image: quay.io/signalfx/splunk-otel-collector:0.41.1
    environment:
      - SPLUNK_ACCESS_TOKEN
      - SPLUNK_REALM
      - SPLUNK_CONFIG=/etc/collector.yaml
    ports:
      - "4317:4317"
      - "6060:6060"
      - "8888:8888"
      - "9080:9080"
      - "9411:9411"
      - "9943:9943"
      - "13133:13133"
      - "14250:14250"
      - "14268:14268"
    volumes:
      - "./collector.yaml:/etc/collector.yaml"
