version: '3'

services:
  public_api:
    build: ./public_api
    environment:
      - OTEL_SERVICE_NAME=public_api
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_RESOURCE_ATTRIBUTES
      - SPLUNK_ACCESS_TOKEN
      - REDIS_URL=redis://cache
    expose:
      - "8000"
    ports:
      - "8000:5000"
    depends_on:
      - "redis"
      - normalize
      - split
      - count
  normalize:
    build: ./normalize
    environment:
      - OTEL_SERVICE_NAME=normalize
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_RESOURCE_ATTRIBUTES
      - SPLUNK_ACCESS_TOKEN
    expose:
      - "5000"
  split:
    build: ./split
    environment:
      - OTEL_SERVICE_NAME=split
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_RESOURCE_ATTRIBUTES
      - SPLUNK_ACCESS_TOKEN
    expose:
      - "5000"
  count:
    build: ./count
    environment:
      - OTEL_SERVICE_NAME=count
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_RESOURCE_ATTRIBUTES
      - SPLUNK_ACCESS_TOKEN
    expose:
      - "5000"
  redis:
    image: redis
    container_name: cache
    expose:
      - "6379"
  collector:
    image: quay.io/signalfx/splunk-otel-collector:0.41.1
    environment:
      - SPLUNK_ACCESS_TOKEN
      - SPLUNK_REALM
      - SPLUNK_TRACE_URL=https://ingest.${SPLUNK_REALM}.signalfx.com/v2/trace
      - SPLUNK_API_URL=https://api.${SPLUNK_REALM}.signalfx.com
      - SPLUNK_INGEST_URL=https://ingest.${SPLUNK_REALM}.signalfx.com
      - SPLUNK_CONFIG=/etc/collector.yaml
    ports:
      - "4317:4317"
      - "6060:6060"
      - "8888:8888"
      - "9080:9080"
      - "9411:9411"
      - "9943:9943"
      - "13133:13133"
      - "14250:14250"
      - "14268:14268"
    volumes:
      - "./collector.yaml:/etc/collector.yaml"
      - "/var/run/docker.sock:/var/run/docker.sock"
