version: '3'

services:
  public_api:
    build: ./public_api
    image: docker.registry:9999/public_api
    expose:
      - "8000"
    ports:
      - "8000:5000"
    depends_on:
      - "redis"
      - normalize
      - split
      - count
  normalize:
    build: ./normalize
    image: docker.registry:9999/normalize
    expose:
      - "5000"
  split:
    build: ./split
    image: docker.registry:9999/split
    expose:
      - "5000"
  count:
    build: ./count
    image: docker.registry:9999/count
    expose:
      - "5000"
  redis:
    image: redis
    container_name: cache
    expose:
      - "6379"
