agent:
  config:
    receivers:
      prometheus_simple/api:
        endpoint: "public-api:8000"
      prometheus_simple/normalize:
        endpoint: "normalize:5000"
      prometheus_simple/split:
        endpoint: "split:5000"
      prometheus_simple/count:
        endpoint: "count:5000"
      receiver_creator:
        receivers:
          smartagent/redis:
            rule: type == "port" && pod.name matches "redis" && port == 6379
            config:
              type: collectd/redis
    service:
      pipelines:
        metrics:
          receivers:
            - hostmetrics
            - kubeletstats
            - prometheus_simple/api
            - prometheus_simple/normalize
            - prometheus_simple/split
            - prometheus_simple/count
            - receiver_creator
    extensions:
      zpages:
        endpoint: 0.0.0.0:55679
